/**
** cps.sql
** $Revision: 
** $Log: cps.sql,v $
** Created 1.0 2005/02/04 3:13:00  rzhtj5
** check in
**
**/

/** CPS_USER Table **/

DROP TABLE CPS_USER CASCADE CONSTRAINTS;

CREATE TABLE CPS_USER (
       USER_ID		NUMBER(10) PRIMARY KEY,
       NETID            VARCHAR2(8) NOT NULL,
       ISACTIVE		CHAR(1) DEFAULT 'Y'
);

DROP SEQUENCE CPS_USER_SEQUENCE;
CREATE SEQUENCE CPS_USER_SEQUENCE START WITH 100;

/** CPS_USER_ROLE Table **/

DROP TABLE CPS_USER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE CPS_USER_ROLE (
       ROLE_ID          NUMBER(10) PRIMARY KEY,
       ROLE             VARCHAR2(30) NOT NULL
);

DROP SEQUENCE CPS_USER_ROLE_SEQUENCE;
CREATE SEQUENCE CPS_USER_ROLE_SEQUENCE START WITH 100;

/** CPS_USER_ROLE_TO_USER Table **/

DROP TABLE CPS_USER_ROLE_TO_USER CASCADE CONSTRAINTS;

CREATE TABLE CPS_USER_ROLE_TO_USER (
       ROLE_ID          NUMBER(10) NOT NULL,
       USER_ID          NUMBER(10) NOT NULL
);

ALTER TABLE CPS_USER_ROLE_TO_USER
       ADD  ( PRIMARY KEY (ROLE_ID, USER_ID) );

CREATE INDEX CPS_USER_ROLE_TO_USER_INDEX ON CPS_USER_ROLE_TO_USER
(
       USER_ID          ASC
);

ALTER TABLE CPS_USER_ROLE_TO_USER
       ADD  ( FOREIGN KEY (USER_ID)
                        REFERENCES CPS_USER );

ALTER TABLE CPS_USER_ROLE_TO_USER
       ADD  ( FOREIGN KEY (ROLE_ID)
                        REFERENCES CPS_USER_ROLE );


----------------- chandra

/** CPS_FILE Table **/

DROP TABLE CPS_FILE CASCADE CONSTRAINTS;

CREATE TABLE  CPS_FILE(
	FILE_ID		INTEGER CONSTRAINT PRIM_FILE_FILEID PRIMARY KEY ,
	USER_ID		INTEGER REFERENCES CPS_USER(USER_ID),
	TXT_FILE_NAME	VARCHAR2(20),
	TXT_AUTHOR	VARCHAR2(20),
	DT_CREATE	DATE,
	COMMENTS	VARCHAR2(50)
);


/** CPS_ATTRIBUTE_TO_FILE Table **/

DROP TABLE CPS_ATTRIBUTE_TO_FILE CASCADE CONSTRAINTS;

CREATE TABLE CPS_ATTRIBUTE_TO_FILE(
	FILE_ID		INTEGER REFERENCES CPS_FILE(FILE_ID),
	ATTRIBUTE_ID	INTEGER CONSTRAINT PRIM_FILE_ATTRIBUTEID PRIMARY KEY,
	USER_ID		INTEGER REFERENCES CPS_USER(USER_ID)
);

 
/** CPS_ATTRIBUTE Table **/

DROP TABLE CPS_ATTRIBUTE CASCADE CONSTRAINTS;

CREATE TABLE CPS_ATTRIBUTE(
	ATTRIBUTE_ID	INTEGER REFERENCES CPS_ATTRIBUTE_TO_FILE (ATTRIBUTE_ID),
	ALIAS		VARCHAR2(20),
	NAME		VARCHAR2(20)
);


/** CPS_ATTRIBUTE Table **/

DROP TABLE CPS_FILE_FACT CASCADE CONSTRAINTS;

CREATE TABLE CPS_FILE_FACT(
	FILE_ID			INTEGER REFERENCES CPS_FILE(FILE_ID),
	USER_ID			INTEGER REFERENCES CPS_USER(USER_ID),
	NUM_FACT_ID		INTEGER CONSTRAINT PRIM_NUMFACTID PRIMARY KEY,
	VOLUME			NUMBER(3),
	VOLUME_PERCENT		NUMBER(3,8),
	YEAR			INTEGER,
	MONTH			INTEGER,
	DRI_ENGNM_ID		INTEGER,
	DRI_MODRANGE_ID		INTEGER,
	DRI_MODVAR_ID		INTEGER,
	DRI_PLATFORM_ID		INTEGER,
	DRI_PRODBRAND_ID	INTEGER,
	DRI_TRAN_ID		INTEGER,
	DRI_VEHMFG_ID		INTEGER,
	GM_CVA_ID		INTEGER,
	GM_CVS_ID		INTEGER,
	GM_DRVPOS_ID		INTEGER,
	GM_ENGNUM_ID		INTEGER,
	GM_MKTIV_ID		INTEGER,
	GM_MODRN_ID		INTEGER,
	GM_PKG_ID		INTEGER,
	GM_TRANSNM_ID		INTEGER,
	GM_VEHLINE_ID		INTEGER,
	GM_VEHSER_ID		INTEGER,
	GM_VPPC_ID		INTEGER,
	GM_VEHSTYLE_ID		INTEGER,
	GM_VEHTYPE_ID		INTEGER,
	DH_CUSTCODE_ID		INTEGER,
	DH_CUSTDESCR_ID		INTEGER,
	DH_CPN_ID		INTEGER,
	DH_DPN_ID		INTEGER,
	DH_BUYERCODE_NO		INTEGER,
	DH_DPNDESCR_ID		INTEGER,
	DH_HTRAC_ID		INTEGER,
	DH_SUPCODE_ID		INTEGER,
	DH_SUPGRP_ID		INTEGER,
	DH_PPN_ID		INTEGER,
	DH_PN_ID		INTEGER,
	DH_PARTYPE_ID		INTEGER,
	DH_PLANT_ID		INTEGER,
	DH_PNDESCR_ID		INTEGER,
	DH_PPNDESCR_ID		INTEGER,
	DH_PRODLINE_ID		INTEGER,
	DH_PRODNAME_ID		INTEGER,
	DH_RESTRICT_ID		INTEGER,
	DH_SUPGRPDESC_ID	INTEGER,
	DH_VOLTYPE_ID		INTEGER,
	DEC_DC_ID		INTEGER,
	DEC_ORIGIN_ID		INTEGER,
	DEC_PN_ID		INTEGER
);


/** CPS_REPORT_TEMPLATE Table **/

DROP TABLE CPS_REPORT_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE CPS_REPORT_TEMPLATE(
	REPORT_TEMPLATE_ID	INTEGER CONSTRAINT PRIM_REPORT_TEMPLATE PRIMARY KEY ,
	USER_ID			INTEGER REFERENCES CPS_USER(USER_ID),
	NAME			VARCHAR2(20),
	DT_CREATE		DATE, 
	XML			CLOB
);


/** CPS_COMPONENT_GROUP_TEMPLATE Table **/

DROP TABLE CPS_COMPONENT_GROUP_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE CPS_COMPONENT_GROUP_TEMPLATE(
	COMPONENT_GROUP_TEMPLATE_ID	INTEGER CONSTRAINT PRIM_COMPONENTREPORT_TEMPLATE PRIMARY KEY ,
	USER_ID				INTEGER REFERENCES CPS_USER(USER_ID),
	NAME				VARCHAR2(20),
	DT_CREATE			DATE, 
	XML				CLOB
);

