/**
** cps.sql
** $Revision: 
** $Log: cps.sql,v $
** Created 1.0 2005/02/04 3:13:00  rzhtj5
** check in
**
**/

/** CPS_USER Table **/

DROP TABLE CPS_USER CASCADE CONSTRAINTS;

CREATE TABLE CPS_USER (
       USER_ID		NUMBER(10) PRIMARY KEY,
       NET_ID           VARCHAR2(8) NOT NULL,
       ISACTIVE		CHAR(1) DEFAULT 'Y'
);

DROP SEQUENCE CPS_USER_SEQUENCE;
CREATE SEQUENCE CPS_USER_SEQUENCE START WITH 100;

/** CPS_USER_ROLE Table **/

DROP TABLE CPS_USER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE CPS_USER_ROLE (
       ROLE_ID          NUMBER(10) PRIMARY KEY,
       ROLE             VARCHAR2(30) NOT NULL
);

DROP SEQUENCE CPS_USER_ROLE_SEQUENCE;
CREATE SEQUENCE CPS_USER_ROLE_SEQUENCE START WITH 100;

/** CPS_USER_ROLE_TO_USER Table **/

DROP TABLE CPS_USER_ROLE_TO_USER CASCADE CONSTRAINTS;

CREATE TABLE CPS_USER_ROLE_TO_USER (
       ROLE_ID          NUMBER(10) NOT NULL,
       USER_ID          NUMBER(10) NOT NULL
);

ALTER TABLE CPS_USER_ROLE_TO_USER
       ADD  ( PRIMARY KEY (ROLE_ID, USER_ID) );

CREATE INDEX CPS_USER_ROLE_TO_USER_INDEX ON CPS_USER_ROLE_TO_USER
(
       USER_ID          ASC
);

ALTER TABLE CPS_USER_ROLE_TO_USER
       ADD  ( FOREIGN KEY (USER_ID)
                        REFERENCES CPS_USER );

ALTER TABLE CPS_USER_ROLE_TO_USER
       ADD  ( FOREIGN KEY (ROLE_ID)
                        REFERENCES CPS_USER_ROLE );


/** CPS_USER_ROLE_VIEW **/

CREATE OR REPLACE VIEW CPS_USER_ROLE_VIEW AS
	select t1.USER_ID, t2.ROLE_ID, t1.NET_ID, t2.ROLE, t1.ISACTIVE
	from CPS_USER t1, CPS_USER_ROLE t2, CPS_USER_ROLE_TO_USER t3
	where t1.USER_ID = t3.USER_ID AND
	t2.ROLE_ID = t3.ROLE_ID
	ORDER BY T1.NET_ID, T2.ROLE


DROP TABLE CPS_FILE CASCADE CONSTRAINTS;

CREATE TABLE  CPS_FILE(
	FILE_ID		INTEGER CONSTRAINT PRIM_FILE_FILEID PRIMARY KEY ,
	USER_ID		INTEGER REFERENCES CPS_USER(USER_ID),
	TXT_FILE_NAME	VARCHAR2(20),
	TXT_AUTHOR	VARCHAR2(20),
	DT_CREATE	DATE,
	COMMENTS	VARCHAR2(50)
);
