/**
** load.sql
** $Revision: 
** $Log: cps.sql,v $
** Created 1.0 2005/02/04 3:40:00  rzhtj5
** check in
**
**/

SET DEFINE OFF
SET SCAN OFF

DELETE FROM CPS_USER_ROLE_TO_USER;
DELETE FROM CPS_USER_ROLE;
DELETE FROM CPS_USER;

/** Load CPS_USER Table **/

INSERT INTO CPS_USER (USER_ID,NET_ID) VALUES (CPS_USER_SEQUENCE.NEXTVAL,'czkshk');
INSERT INTO CPS_USER (USER_ID,NET_ID) VALUES (CPS_USER_SEQUENCE.NEXTVAL,'vz86k2');
INSERT INTO CPS_USER (USER_ID,NET_ID) VALUES (CPS_USER_SEQUENCE.NEXTVAL,'rzhtj5');


/** Load CPS_USER_ROLE Table **/

INSERT INTO CPS_USER_ROLE (ROLE_ID,ROLE) VALUES (CPS_USER_ROLE_SEQUENCE.NEXTVAL,'Admin');
INSERT INTO CPS_USER_ROLE (ROLE_ID,ROLE) VALUES (CPS_USER_ROLE_SEQUENCE.NEXTVAL,'Scripting');
INSERT INTO CPS_USER_ROLE (ROLE_ID,ROLE) VALUES (CPS_USER_ROLE_SEQUENCE.NEXTVAL,'Analysis');


/** Load CPS_USER_ROLE_TO_USER Table **/

INSERT INTO CPS_USER_ROLE_TO_USER (ROLE_ID,USER_ID) SELECT t1.ROLE_ID, t2.USER_ID FROM CPS_USER_ROLE t1, CPS_USER t2 WHERE t1.ROLE = 'Admin' AND t2.NET_ID = 'vz86k2';
INSERT INTO CPS_USER_ROLE_TO_USER (ROLE_ID,USER_ID) SELECT t1.ROLE_ID, t2.USER_ID FROM CPS_USER_ROLE t1, CPS_USER t2 WHERE t1.ROLE = 'Admin' AND t2.NET_ID = 'czkshk';
INSERT INTO CPS_USER_ROLE_TO_USER (ROLE_ID,USER_ID) SELECT t1.ROLE_ID, t2.USER_ID FROM CPS_USER_ROLE t1, CPS_USER t2 WHERE t1.ROLE = 'Admin' AND t2.NET_ID = 'rzhtj5';
INSERT INTO CPS_USER_ROLE_TO_USER (ROLE_ID,USER_ID) SELECT t1.ROLE_ID, t2.USER_ID FROM CPS_USER_ROLE t1, CPS_USER t2 WHERE t1.ROLE = 'Scripting' AND t2.NET_ID = 'rzhtj5';
INSERT INTO CPS_USER_ROLE_TO_USER (ROLE_ID,USER_ID) SELECT t1.ROLE_ID, t2.USER_ID FROM CPS_USER_ROLE t1, CPS_USER t2 WHERE t1.ROLE = 'Analysis' AND t2.NET_ID = 'rzhtj5';


/** Load CPS_FILE data **/
INSERT INTO CPS_FILE VALUES (101,102,'AUTOPART-1','PAUL','17-FEB-2005','Erwin paul can access');
INSERT INTO CPS_FILE VALUES (102,102,'AUTOPART-2','PAUL','18-FEB-2005','Erwin paul can access');
INSERT INTO CPS_FILE VALUES (103,102,'AUTOPART-3','PAUL','19-FEB-2005','Erwin paul can access');